name = "WebDriver"
uuid = "05625dda-b54a-434a-8c43-5c7937dfa4f0"
authors = ["José Bayoán Santiago Calderón <naoyabpr@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
Documenter = "0.24"
HTTP = "0.8"
JSON3 = "0.1, 1.0"
Parameters = "0.12"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
